config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :videos do
    collection do
      resource :sync, only: [:create]
    end

    resource :transcribe, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "videos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/video.rb
class Video < ApplicationRecord
  scope :captioned, ->{ where(captions: true) }
  scope :uncaptioned, ->{ where(captions: false) }

  broadcasts_refreshes
  after_commit :transcribe, on: [:create, :update], unless: :captions?

  def download_url
    "https://#{Rails.application.credentials.bunny_zone}.b-cdn.net/#{guid}/play_240p.mp4"
  end

  def thumbnail_url
    "https://#{Rails.application.credentials.bunny_zone}.b-cdn.net/#{guid}/#{thumbnail_filename}"
  end

  def transcribe
    TranscribeJob.perform_later(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/syncs_controller.rb
class SyncsController < ApplicationController
  def create
    SyncJob.perform_later
    redirect_back_or_to root_path, notice: "Syncing will begin shortly"
  end
end

app/controllers/transcribes_controller.rb
class TranscribesController < ApplicationController
  before_action :set_video

  def create
    @video.transcribe
    redirect_back_or_to @video, notice: "Transcribing will begin shortly."
  end

  private

  def set_video
    @video = Video.find(params[:video_id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @pagy, @videos = pagy Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:library_id, :guid, :title, :captions, :thumbnail_filename, :views_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TranscriptionMachine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_with(model: video, class: "contents") do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :library_id %>
    <%= form.text_field :library_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :guid %>
    <%= form.text_field :guid, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :captions %>
    <%= form.check_box :captions, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>" class="flex gap-4">
  <%= image_tag video.thumbnail_url, class: "h-32 w-48 rounded-lg" %>
  <div>
    <h2 class="flex gap-2 items-center font-semibold">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6 <%= class_names("text-green-500" => video.captions?, "text-gray-500" => !video.captions?) %>">
        <path fill-rule="evenodd" d="M9 1.5H5.625c-1.036 0-1.875.84-1.875 1.875v17.25c0 1.035.84 1.875 1.875 1.875h12.75c1.035 0 1.875-.84 1.875-1.875V12.75A3.75 3.75 0 0 0 16.5 9h-1.875a1.875 1.875 0 0 1-1.875-1.875V5.25A3.75 3.75 0 0 0 9 1.5Zm6.61 10.936a.75.75 0 1 0-1.22-.872l-3.236 4.53L9.53 14.47a.75.75 0 0 0-1.06 1.06l2.25 2.25a.75.75 0 0 0 1.14-.094l3.75-5.25Z" clip-rule="evenodd" />
        <path d="M12.971 1.816A5.23 5.23 0 0 1 14.25 5.25v1.875c0 .207.168.375.375.375H16.5a5.23 5.23 0 0 1 3.434 1.279 9.768 9.768 0 0 0-6.963-6.963Z" />
      </svg>
      <%= video.title %>
    </h2>
    <p class="my-5">
      <strong class="block font-medium mb-1">Library:</strong>
      <%= video.library_id %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Guid:</strong>
      <%= video.guid %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Captions:</strong>
      <%= video.captions %>
    </p>

    <% if action_name != "show" %>
      <%= link_to "View", video, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to "Edit", edit_video_path(video), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= button_to "Transcribe", video_transcribe_path(video), method: :post, form_class: "inline-block", class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </div>
</div>

app/views/videos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing video</h1>

  <%= render "form", video: @video %>

  <%= link_to "Show this video", @video, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to videos", videos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/videos/index.html.erb
<%= turbo_stream_from "videos" %>
<% @videos.each do |video| %>
  <%= turbo_stream_from video %>
<% end %>
<div class="w-full mb-16">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Videos" %>

  <div class="flex justify-between items-center mb-8">
    <h1 class="font-bold text-4xl">Videos</h1>
    <div class="flex items-center gap-2">
      <%= button_to "Sync", sync_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
      <%= link_to "Jobs", MissionControl::Jobs::Engine.routes.url_helpers.root_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  </div>

  <div id="videos" class="min-w-full flex flex-col gap-4">
    <% @videos.each do |video| %>
      <%= render video %>
    <% end %>
  </div>

  <% if @pagy.pages > 1 %>
    <div class="mt-8">
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/videos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New video</h1>

  <%= render "form", video: @video %>

  <%= link_to "Back to videos", videos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/videos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @video %>

    <%= button_to "Transcribe", video_transcribe_path(@video), method: :post, form_class: "inline-block", class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this video", edit_video_path(@video), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to videos", videos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block">
      <%= button_to "Destroy this video", @video, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium bg-red-500 text-white" %>
    </div>
  </div>
</div>